Добавлено описание и доработаны модели продуктов
chilling-goods/Chilling.Goods.Api pull request #2
Opened 2022-08-21 12:45 UTC by CITHARISTA

2022-08-21 18:38 UTC, sickwick requested changes

2022-08-21 18:38 UTC, sickwick commented on Chilling.Goods.Api/Models/CatalogVm.cs
> +        [Display(Name = "Id")]
Это зачем?

2022-08-21 18:38 UTC, sickwick commented on Chilling.Goods.Api/Controllers/Exmpl.cs
> +public static class Exmpl
Мб тогда совсем удалим класс?

2022-08-21 18:38 UTC, sickwick commented on Chilling.Goods.Api/Controllers/CatalogController.cs
> +    [Route("api/[controller]")]
Лучше сделать [Route("[controller]")] а api настроить глобальным префиксом для всего приложения

2022-08-22 07:10 UTC, sickwick commented on Chilling.Goods.Api/Models/CatalogVm.cs
> +        [Display(Name = "Id")]
я про [Display(Name = "Id")]

2022-08-22 09:54 UTC, CITHARISTA commented on Chilling.Goods.Api/Models/CatalogVm.cs
> +        [Display(Name = "Id")]
аналог jsonproperty, без разницы что использовать

2022-08-22 09:54 UTC, CITHARISTA commented on Chilling.Goods.Api/Controllers/Exmpl.cs
> +public static class Exmpl
да, потом делитну, просто подумал вдруг тебе нужно будет))

2022-08-22 09:55 UTC, CITHARISTA commented on Chilling.Goods.Api/Controllers/CatalogController.cs
> +    [Route("api/[controller]")]
можно

2022-08-22 16:53 UTC, merged